FROM node:16-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm config set strict-ssl false \
    && npm ci
COPY . ./
RUN npm run build

FROM nginx:latest AS production
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx/conf.d/default.conf /etc/nginx/conf.d

EXPOSE 80
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]